import { Config } from "./config";
import { ResponseMessageHelper } from "./../helpers/response.message.helper";
import { TitleHelper } from "./../helpers/title.helper";
import { TimeHelper } from "./../helpers/time.helper";
import { MediaHelper } from "./../helpers/media.helper";
import { MediaHandler } from "./../handlers/media.handler";
import { MediaVariables } from "./../graphql/variables/media.variables";
import { AnimeVariables } from "./../graphql/variables/anime.variables";
import { Ping } from "./ping";
import { Color } from "./colors";
import { HelpCommand } from "./../command/help.command";
import { EmbedHelper } from "./../helpers/embed.helper";
import { BotCommand } from "./../command/bot.command";
import { MessageHelper } from "../helpers/message.helper";
import { MessageHandler } from "../handlers/message.handler";
import { GraphQL } from "../graphql/graphql";
import { Anilist } from "./anilist";
import { ResponseHandler } from "../handlers/response.handler";
import { MediaResult } from "./media.result";
import { ClientManager } from "./client";
import { ExampleCommand } from "../command/example.command";

export class Container {
  public static Config: Config;
  public static ClientManager: ClientManager;
  public static MessageHelper: MessageHelper;
  public static MediaHelper: MediaHelper;
  public static TimeHelper: TimeHelper;
  public static TitleHelper: TitleHelper;
  public static ResponseMessageHelper: ResponseMessageHelper;
  public static EmbedHelper: EmbedHelper;
  public static MessageHandler: MessageHandler;
  public static ResponseHandler: ResponseHandler;
  public static MediaHandler: MediaHandler;
  public static CommandExample: ExampleCommand;
  public static BotCommand: BotCommand;
  public static HelpCommand: HelpCommand;
  public static AnimeVariables: AnimeVariables;
  public static MediaVariables: MediaVariables;
  public static MediaResult: MediaResult;
  public static GraphQL: GraphQL;
  public static Anilist: Anilist;
  public static Color: Color;
  public static Ping: Ping;
}
